import Foundation

/// Per-user launchd LaunchAgent generation + lifecycle (PRD v2 §7.4, §8.2).
///
/// The original tool shipped a hand-written plist with a hardcoded path and a
/// personal bundle id (`com.bartturczynski.ccfix-watch`, plus an absolute
/// `/Users/<name>/…` program path). This module fixes both: the label is a
/// generic reverse-DNS string with no personal identifier, and the program path
/// is resolved from the running binary at install time rather than baked in.
///
/// The plist *string* is generated by a pure function (`plist`) so it is fully
/// unit-testable; all filesystem and `launchctl` I/O lives behind the injectable
/// `LaunchAgentManager`.
public enum LaunchAgent {
    /// The LaunchAgent label / plist basename. Generic reverse-DNS, **not** a
    /// personal identifier (§7.4). Derived from the resolved tool name (§11),
    /// alongside the binary and tap repo.
    public static let label = "io.unbreak.watch"

    /// The launchd program-arguments tail appended after the binary path: run the
    /// watcher in its mutating, fix-on-copy mode (§7).
    public static let programFlags = ["--watch"]

    /// Generate the LaunchAgent plist XML.
    ///
    /// - Parameters:
    ///   - label: the launchd label (also the plist basename).
    ///   - binaryPath: absolute path to the `unbreak` executable to launch.
    ///   - standardOutPath: file the agent's stdout+stderr are redirected to.
    /// - Returns: a complete, well-formed plist document.
    ///
    /// `RunAtLoad` + `KeepAlive` mirror the original archived plist: start at
    /// login and restart if the daemon ever exits.
    public static func plist(
        label: String = LaunchAgent.label,
        binaryPath: String,
        standardOutPath: String
    ) -> String {
        let programArguments =
            ([binaryPath] + programFlags)
            .map { "        <string>\(xmlEscape($0))</string>" }
            .joined(separator: "\n")

        return """
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>Label</key>
                <string>\(xmlEscape(label))</string>

                <key>ProgramArguments</key>
                <array>
            \(programArguments)
                </array>

                <!-- Start at login and restart if it ever exits. -->
                <key>RunAtLoad</key>
                <true/>
                <key>KeepAlive</key>
                <true/>

                <!-- Process stdout/stderr (the structured decision log is separate:
                     ~/Library/Logs/unbreak.log, written by the daemon itself, §7.3). -->
                <key>StandardOutPath</key>
                <string>\(xmlEscape(standardOutPath))</string>
                <key>StandardErrorPath</key>
                <string>\(xmlEscape(standardOutPath))</string>
            </dict>
            </plist>

            """
    }

    /// Minimal XML text escaping for the values we interpolate (filesystem paths
    /// and the label). Covers the five predefined entities.
    static func xmlEscape(_ value: String) -> String {
        var out = ""
        out.reserveCapacity(value.count)
        for character in value {
            switch character {
            case "&": out += "&amp;"
            case "<": out += "&lt;"
            case ">": out += "&gt;"
            case "\"": out += "&quot;"
            case "'": out += "&apos;"
            default: out.append(character)
            }
        }
        return out
    }
}

/// Installs, removes, and reports on the `unbreak` LaunchAgent (§8.2).
///
/// Every side effect — locating the binary, writing the plist, invoking
/// `launchctl`, and removing the file — is injected, so `install`/`uninstall` can
/// be exercised end-to-end against in-memory fakes with no real launchd contact.
public struct LaunchAgentManager {
    /// The outcome of an install/uninstall, with a user-facing message and an
    /// exit code for the CLI to return.
    public struct Outcome: Equatable {
        public var message: String
        public var exitCode: Int32
        public init(message: String, exitCode: Int32) {
            self.message = message
            self.exitCode = exitCode
        }
    }

    /// `~/Library/LaunchAgents`, where per-user agents live.
    public var launchAgentsDirectory: URL
    /// Where the daemon's stdout/stderr is redirected.
    public var standardOutPath: String
    /// Resolves the absolute path of the `unbreak` binary to launch, or `nil` if it
    /// cannot be determined (in which case install refuses rather than guessing).
    public var binaryPath: () -> String?
    /// Writes `contents` to `url`; throws on failure.
    public var writeFile: (_ contents: String, _ url: URL) throws -> Void
    /// Removes the file at `url`; a missing file is not an error.
    public var removeFile: (_ url: URL) throws -> Void
    /// Reports whether a file exists at `url` (used by uninstall to detect a no-op).
    public var fileExists: (_ url: URL) -> Bool
    /// Runs `launchctl` with the given arguments and returns its exit status.
    public var runLaunchctl: (_ arguments: [String]) -> Int32

    public init(
        launchAgentsDirectory: URL,
        standardOutPath: String,
        binaryPath: @escaping () -> String?,
        writeFile: @escaping (_ contents: String, _ url: URL) throws -> Void,
        removeFile: @escaping (_ url: URL) throws -> Void,
        fileExists: @escaping (_ url: URL) -> Bool,
        runLaunchctl: @escaping (_ arguments: [String]) -> Int32
    ) {
        self.launchAgentsDirectory = launchAgentsDirectory
        self.standardOutPath = standardOutPath
        self.binaryPath = binaryPath
        self.writeFile = writeFile
        self.removeFile = removeFile
        self.fileExists = fileExists
        self.runLaunchctl = runLaunchctl
    }

    /// The plist file path: `~/Library/LaunchAgents/<label>.plist`.
    public var plistURL: URL {
        launchAgentsDirectory.appendingPathComponent("\(LaunchAgent.label).plist")
    }

    /// The launchd domain target for the current user, e.g. `gui/501`.
    static func guiDomain() -> String {
        "gui/\(getuid())"
    }

    /// Generate + write the plist and bootstrap it into the user's GUI domain.
    ///
    /// `bootout` is attempted first (and its failure ignored) so a re-install over
    /// an already-loaded agent succeeds rather than tripping launchd's
    /// "service already loaded" error.
    public func install() -> Outcome {
        guard let path = binaryPath(), !path.isEmpty else {
            return Outcome(
                message: "unbreak: could not resolve the unbreak binary path; agent not installed",
                exitCode: 1
            )
        }

        let document = LaunchAgent.plist(binaryPath: path, standardOutPath: standardOutPath)
        do {
            try writeFile(document, plistURL)
        } catch {
            return Outcome(
                message: "unbreak: failed to write \(plistURL.path): \(error)",
                exitCode: 1
            )
        }

        let domain = Self.guiDomain()
        _ = runLaunchctl(["bootout", "\(domain)/\(LaunchAgent.label)"])
        let status = runLaunchctl(["bootstrap", domain, plistURL.path])
        guard status == 0 else {
            return Outcome(
                message: """
                    unbreak: wrote the plist but `launchctl bootstrap` failed (status \(status)).
                    Try `launchctl bootstrap \(domain) \(plistURL.path)`, or log out and back in.
                    """,
                exitCode: 1
            )
        }
        return Outcome(
            message: """
                unbreak: watcher LaunchAgent installed (\(LaunchAgent.label)) and started.
                It runs at login and fixes the clipboard on copy only when every gate passes.
                Remove it any time with `unbreak uninstall-agent`.
                """,
            exitCode: 0
        )
    }

    /// Bootout the agent and remove its plist. A missing plist is reported as an
    /// already-uninstalled no-op rather than an error.
    public func uninstall() -> Outcome {
        let existed = fileExists(plistURL)
        _ = runLaunchctl(["bootout", "\(Self.guiDomain())/\(LaunchAgent.label)"])
        do {
            try removeFile(plistURL)
        } catch {
            return Outcome(
                message: "unbreak: failed to remove \(plistURL.path): \(error)",
                exitCode: 1
            )
        }
        let message =
            existed
            ? "unbreak: watcher LaunchAgent removed (\(LaunchAgent.label)); "
                + "it will not run at login."
            : "unbreak: no watcher LaunchAgent was installed; nothing to do."
        return Outcome(message: message, exitCode: 0)
    }
}

extension LaunchAgentManager {
    /// The production manager: real `~/Library/LaunchAgents`, `FileManager`, and a
    /// `launchctl` subprocess. The binary path is resolved from the running
    /// executable (made absolute) so the plist never hardcodes a per-user path.
    public static func system(
        home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) -> LaunchAgentManager {
        let agents = home.appendingPathComponent("Library/LaunchAgents", isDirectory: true)
        let logs = home.appendingPathComponent("Library/Logs", isDirectory: true)
        return LaunchAgentManager(
            launchAgentsDirectory: agents,
            standardOutPath: logs.appendingPathComponent("unbreak.watch.log").path,
            binaryPath: resolveBinaryPath,
            writeFile: { contents, url in
                try FileManager.default.createDirectory(
                    at: url.deletingLastPathComponent(),
                    withIntermediateDirectories: true
                )
                try contents.write(to: url, atomically: true, encoding: .utf8)
            },
            removeFile: { url in
                if FileManager.default.fileExists(atPath: url.path) {
                    try FileManager.default.removeItem(at: url)
                }
            },
            fileExists: { FileManager.default.fileExists(atPath: $0.path) },
            runLaunchctl: { arguments in
                #if canImport(Foundation) && !os(Linux)
                let process = Process()
                process.executableURL = URL(fileURLWithPath: "/bin/launchctl")
                process.arguments = arguments
                do {
                    try process.run()
                    process.waitUntilExit()
                    return process.terminationStatus
                } catch {
                    return -1
                }
                #else
                return -1
                #endif
            }
        )
    }

    /// Resolve the running executable to an absolute path for the plist.
    ///
    /// `Bundle.main.executablePath` returns the absolute path of the current
    /// binary; we fall back to making `argv[0]` absolute against the working
    /// directory. (Homebrew users are steered to `brew services`, which writes its
    /// own versioned plist — see the install caveat, §9.)
    static func resolveBinaryPath() -> String? {
        if let path = Bundle.main.executablePath, !path.isEmpty {
            return path
        }
        let argv0 = CommandLine.arguments.first ?? ""
        guard !argv0.isEmpty else { return nil }
        if argv0.hasPrefix("/") { return argv0 }
        return FileManager.default.currentDirectoryPath + "/" + argv0
    }
}
